name: Build

on:
  repository_dispatch:
  push:
    branches: main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v2.3.1

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Project Dependencies
        run: npm ci
      
      - name: Build
        run: npm run build

      - name: Copy Favicons
        run: cp -rp ./favicons/* ./public
      
      - name: Verify build
        run: ls -la public

      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r public.zip public

      - name: Upload image artifact
        uses: actions/upload-artifact@v2
        with:
          name: public.zip
          path: public.zip

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v2
      
      - name: Display structure of downloaded files
        run: ls -R
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: Wierszoterapie ${{ github.sha }}
          draft: true
          prerelease: false
      
      - name: Upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: public.zip/public.zip
          asset_name: public.zip
          asset_content_type: application/zip
